"""lol

Revision ID: a18d9c9af721
Revises: 6534571f5b5d
Create Date: 2018-11-21 12:43:29.951688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18d9c9af721'
down_revision = '6534571f5b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('actual_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'actual_comment')
    # ### end Alembic commands ###
